name: Pipeline de develop

on:
  push:
    branches:
      - develop

jobs:
  ci-program:
    uses: PePires58/ReusableWorkflows/.github/workflows/006_dotnet_build.yaml@main
    with:
      working-directory: ./
      execute-unit-tests: true
      dotnet-version: '8.0'